version: '3.9'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring

volumes:
  rabbitmq:
networks:
  rabbitmq:
    driver: bridge
  monitoring:
    driver: bridge